version: "3.8"

services:
  backend:
    build:
      context: ./pouswapback
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./pouswapfront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pouswap
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306" # TODO: Adapter le port si nécessaire
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
