version: "3.9"
services:
  backend:
    build:
      context: ./pouswapback
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./pouswapfront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:15.4-alpine
    platform: linux/amd64
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-changeme}
      POSTGRES_USER: ${DB_USER:-changeme}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.3
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@exemple.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4admin
    ports:
      - "80:80"
